### ISSUE TITLE
any instruction to import your code and data

### ISSUE THREAD

**Issue by yuxh** [databricks/Spark-The-Definitive-Guide#16]
It's my first time using databricks , I don't find the way to import your code and data to databricks directly(only found something like upload file, import by URL..).  Could you write in readme or just give the link instruction?

**Comment by taodsqi** [comment]
It is still on their ToDo list unfortunately.

**Comment by anabranch** [comment]
Thanks for bringing this up. I thought that we had already written this down but I couldn't find it. I'll take a look at this over the next couple of days and setup the instructions.

**Comment by antgross** [comment]
Is there any update on this issue?

**Comment by anabranch** [comment]
https://github.com/databricks/Spark-The-Definitive-Guide/blob/master/README.md#instructions-for-importing

added some instructions. You don't actually have to import the data - it's all in Databricks for you. Let me know if it's unclear.
