### ISSUE TITLE
ch3 sample code error

### ISSUE THREAD

**Issue by yuxh** [databricks/Spark-The-Definitive-Guide#25]
```
// in Scala
case class Flight(DEST_COUNTRY_NAME: String,
                  ORIGIN_COUNTRY_NAME: String,
                  count: BigInt)
val flightsDF = spark.read
  .parquet("/data/flight-data/parquet/2010-summary.parquet/")
val flights = flightsDF.as[Flight]
```
error: Unable to find encoder for type stored in a Dataset.  Primitive types (Int, String, etc) and Product types (case classes) are supported by importing spark.implicits._  Support for serializing other types will be added in future releases.
       val flights = flightsDF.as[Flight]

**Comment by anabranch** [comment]
Did you try importing `spark.implicits._` ?

**Comment by yuxh** [comment]
I've solve this problem. But I think it should be take as a issue since your book and code doesn't mention this import :)

**Comment by Ravi19945** [comment]
> I've solve this problem. But I think it should be take as a issue since your book and code doesn't mention this import :)

Could you please let me know what I need to do to get rid of below error.

scala> val flights = flightsDF.as[Flight]
<console>:31: error: not found: type Flight
       val flights = flightsDF.as[Flight]
