### ISSUE TITLE
chapter 24 missing python code

### ISSUE THREAD

**Issue by quagly** [databricks/Spark-The-Definitive-Guide#27]
The end of Chapter 24 is scala only.  Is this intentional?  

The training summary and persisting and applying models are Scala only.

I was able to get the summary to work in python3 with Spark 2.3, but not the persist and apply.   Can python be added to the code?

`
trainedPipeline = tvsFitted.bestModel

lrBestModel = trainedPipeline.stages[1]

lrBestModel.summary.objectiveHistory`

**Comment by anabranch** [comment]
I don't believe there are python APIs for it, that's why it wasn't added.
