### ISSUE TITLE
Was this line even tested ? There is no closing quote for the column name

### ISSUE THREAD

**Issue by neeleshkumar-mannur** [databricks/Spark-The-Definitive-Guide#29]
https://github.com/databricks/Spark-The-Definitive-Guide/blob/3255bc360e3cd8c3d9393b8d8c4e127b4358e044/code/A_Gentle_Introduction_to_Spark-Chapter_2_A_Gentle_Introduction_to_Spark.scala#L66

**Comment by anabranch** [comment]
Yes, it was. In Scala, this resolves as an identifier. We mention that a single quote resolves this way in the book. [Read more here](https://stackoverflow.com/questions/918590/what-does-a-single-apostrophe-mean-in-scala).
