### ISSUE TITLE
Ch_9 running SQLite in Databricks

### ISSUE THREAD

**Issue by johnnyjw** [databricks/Spark-The-Definitive-Guide#33]
Hi 
Is it possible to run the JDBC SQLite code in Databricks Community Edition?
If so how would I set this up?

Thanks
Jonathan

**Comment by anabranch** [comment]
You should be able to prepend "/dbfs" to access it using local APIs. For instance: https://docs.databricks.com/user-guide/dbfs-databricks-file-system.html#access-dbfs-using-local-file-apis
