### ISSUE TITLE
Chapter 3: Creating Rows typo

### ISSUE THREAD

**Issue by Italosayan** [databricks/Spark-The-Definitive-Guide#7]
On the example:
myRow.getInt(2) // String
It should be 
myRow.getInt(2) // Int 
right?

**Comment by anabranch** [comment]
If I recall correctly, in the book this is to show that it would be an error. Are you sure you're reading through the book and not just the code :) ?

**Comment by Italosayan** [comment]
Hey bill!
I'm reading and running everything.
So spark will not follow if you change the type on scala?

![screen shot 2018-03-30 at 12 55 15 pm](https://user-images.githubusercontent.com/17087438/38145910-9bcf8e42-3419-11e8-884c-af377fbc89e3.png)

**Comment by anabranch** [comment]
Oh you're talking about the comment? Is that the point of confusion? Could you clarify again?

**Comment by Italosayan** [comment]
yeah. The comment.

Thank you!

**Comment by anabranch** [comment]
gotcha, yes that's probably correct! Thanks
