### ISSUE TITLE
Not able to locate files in databricks-datasets

### ISSUE THREAD

**Issue by hajimurtaza** [databricks/Spark-The-Definitive-Guide#9]
Could u please give proper instruction for path to data uploaded in databricks-datasets?

Also I am not able to load the data folder which is saved locally , directly to my databricks cluster and uploading each file seperately is really  cumbursome?
Is there any solution for that?

**Comment by hajimurtaza** [comment]
Ok so i was able to find this path,
/databricks-datasets/definitive-guide/data/

Kindly update it or if possible i can create a PR and update it.

**Comment by anabranch** [comment]
Yeah we just uploaded it yesterday and I haven't had a chance to do the editing. If you want to take a quick crack at a PR it'd be much appreciated.
